# Utiliser une image de base mysql officielle

FROM mysql:5.7
# Environnement variables 
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DEFAULT_AUTHENTICATION_PLUGIN=mysql_native_password
# Ajouter votre fichier SQL dump
COPY recettes.sql /docker-entrypoint-initdb.d/

# Exécuter le script SQL lors du démarrage du conteneur
#CMD ["mysql", "-uroot", "-p $MYSQL_ROOT_PASSWORD", "-e", "source /docker-entrypoint-initdb.d/recettes.sql"]
# Default command to start MySQL 
CMD ["mysqld"]